In [1]:
import numpy as np
import sussix as nafflib




#-----
# Henon map tune
Q_h = 0.2064898024701758
#-----
example_signals = {}
for x_start,label in zip([0.1,0.3,0.51],['low_J','mid_J','high_J']):
    example_signals[label] = nafflib.henon_map(x_start,0.35*x_start,Q_h,int(3e4))



# def test_parse_real():

for label,signal in example_signals.items():
    # Extracting signal
    x,px = signal
    z    = x - 1j*px
    N    = np.arange(len(z))


    # Choosing number of harmonics
    n_harm = 7

    # x-px lines
    # Take more here, since some might repeat
    spectrum_z = nafflib.harmonics(z,num_harmonics = 2*n_harm,window_order = 2,window_type = 'hann')
    r_z,_,_ = nafflib.find_linear_combinations(spectrum_z[1],fundamental_tunes= [spectrum_z[1][0]])

    # x-only lines
    spectrum_x = nafflib.harmonics(x,num_harmonics = n_harm,window_order = 2,window_type = 'hann')
    r_x,_,_ = nafflib.find_linear_combinations(spectrum_x[1],fundamental_tunes= [spectrum_x[1][0]])

    # Scanning x-lines and comparing with z-lines
    errors_Q = []
    errors_A = []
    for res,A,freq in zip(r_x,spectrum_x[0],spectrum_x[1]):
        spec_z_index = r_z.index(res)
        errors_Q.append(spectrum_z[1][spec_z_index]-freq)
        errors_A.append(np.abs(spectrum_z[0][spec_z_index])-np.abs(A))

    print(errors_Q)
    assert np.allclose(errors_Q,0,atol=1e-15,rtol=0), f'Q difference too large between x-only and x-px, for particle@{label}'
    assert np.allclose(errors_A,0,atol=1e-1,rtol=0),  f'|A| difference too large between x-only and x-px, for particle@{label}'



[0.0, 4.717795933935042e-19, 0.0, 5.551115123125783e-17, 0.0, -7.667477763817487e-16, -1.942890293094024e-16]
[0.0, 1.8986436306495494e-19, 0.0, 0.0, -2.7755575615628914e-17, -1.734723475976807e-18, 0.0]
[0.0, -7.510699721699958e-20, -5.551115123125783e-17, 0.0, 0.0, 3.469446951953614e-18, 5.551115123125783e-17]


In [24]:
spectrum_z = nafflib.harmonics(z,num_harmonics = 20,window_order = 2,window_type = 'hann')
r_z,_,_ = nafflib.find_linear_combinations(spectrum_z[1],fundamental_tunes= [spectrum_z[1][0]])
nafflib.find_linear_combinations(spectrum_z[1],fundamental_tunes= [spectrum_z[1][0]],to_pandas=True)

resonance           err          freq
0     (1, 0)  0.000000e+00  1.956222e-01
1     (0, 0)  7.476448e-20 -7.476448e-20
2     (2, 0)  0.000000e+00  3.912445e-01
3    (-2, 0)  0.000000e+00 -3.912445e-01
4    (-1, 0)  0.000000e+00 -1.956222e-01
5    (6, -1)  0.000000e+00  1.737334e-01
6    (-3, 1)  0.000000e+00  4.131333e-01
7    (-4, 1)  5.551115e-17  2.175110e-01
8    (3, -1)  5.551115e-17 -4.131333e-01
9    (-5, 1)  5.204170e-17  2.188879e-02
10   (5, -1)  4.163336e-17 -2.188879e-02
11   (7, -1)  0.000000e+00  3.693557e-01
12   (-7, 1)  5.551115e-17 -3.693557e-01
13   (-6, 1)  2.775558e-17 -1.737334e-01
14   (6, -1)  2.188879e-02  1.518447e-01
15   (-8, 2)  1.110223e-16  4.350221e-01
16  (-10, 2)  1.387779e-16  4.377759e-02
17   (8, -2)  5.551115e-17 -4.350221e-01
18   (-9, 2)  8.326673e-17  2.393998e-01
19  (10, -2)  1.457168e-16 -4.377759e-02

In [2]:
spectrum = nafflib.harmonics(x,num_harmonics = 10,window_order = 2,window_type = 'hann')
r_val,err,freq = nafflib.find_linear_combinations(spectrum[1],fundamental_tunes= [spectrum[1][0]])
nafflib.find_linear_combinations(spectrum[1],fundamental_tunes= [spectrum[1][0]],to_pandas=True)

resonance           err          freq
0    (1, 0)  0.000000e+00  1.956222e-01
1    (0, 0)  3.425197e-22  3.425197e-22
2    (2, 0)  5.551115e-17  3.912445e-01
3   (6, -1)  0.000000e+00  1.737334e-01
4   (-3, 1)  0.000000e+00  4.131333e-01
5   (-5, 1)  4.857226e-17  2.188879e-02
6   (-4, 1)  0.000000e+00  2.175110e-01
7   (7, -1)  5.551115e-17  3.693557e-01
8   (6, -1)  2.188879e-02  1.518447e-01
9   (-8, 2)  5.551115e-17  4.350221e-01

In [11]:
spectrum_z = nafflib.harmonics(z,num_harmonics = 20,window_order = 2,window_type = 'hann')
r_z,_,_ = nafflib.find_linear_combinations(spectrum_z[1],fundamental_tunes= [spectrum_z[1][0]])

spectrum_x = nafflib.harmonics(x,num_harmonics = 10,window_order = 2,window_type = 'hann')
r_x,_,_ = nafflib.find_linear_combinations(spectrum_x[1],fundamental_tunes= [spectrum_x[1][0]])

In [41]:
np.allclose(errors_Q,0,atol=1e-15,rtol=0)
np.allclose(errors_A,0,atol=1e-1,rtol=0)

True

In [36]:
errors_A

[-0.005342570710920036,
 0.02533138412199637,
 -0.0006208383251311289,
 -0.000640367656509367,
 -0.0005142214027064763,
 -0.004269818088551517,
 0.00010880616117234926,
 4.256921561069434e-05]

In [30]:
np.allclose(errors,0,atol=1e-15,rtol=0)

True

In [3]:
nafflib.harmonics(z,num_harmonics = 1,window_order = 2,window_type = 'hann')

(array([0.09793859-0.04094931j]), array([0.20608871]))

In [10]:
z = z1
nafflib.harmonics(z,num_harmonics = 1,window_order = 2,window_type = 'hann')

checking globals: False


(array([0.09793859-0.04094931j]), array([0.20608871]))

In [2]:
%%timeit
nafflib.harmonics(z,num_harmonics = 1,window_order = 2,window_type = 'hann')

752 ms ± 14.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [2]:
%%timeit
nafflib.harmonics(z1,num_harmonics = 1,window_order = 2,window_type = 'hann')

714 ms ± 44.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
nafflib.tune(z)

0.41217742543313285

In [4]:
z

NameError: name 'z' is not defined

In [12]:
"z" in globals()

True

In [58]:
import sussix as nafflib
#-----
# Henon map tune
Q_h = 0.2064898024701758
#-----
example_signals = {}
for x_start,label in zip([0.1,0.3,0.51],['low_J','mid_J','high_J']):
    example_signals[label] = nafflib.henon_map(x_start,0.35*x_start,Q_h,int(3e4))



x,px = example_signals['mid_J']
z    = x - 1j*px

nafflib.tune(z)

0.20243887605835303

In [60]:
print(z)
nafflib.harmonics(x=z,num_harmonics = 10,window_order = 2,window_type = 'hann',to_pandas=True);
print(z)

[-8.81112370e-04-0.0001099j  -1.91167116e-05-0.00013003j
 -6.36161773e-04-0.00088073j ...  6.21538020e-04+0.00177029j
  7.10953408e-04-0.00122961j -9.04814784e-04-0.00046324j]
[-2.26023324e-05+2.68823579e-06j -3.36352155e-05-1.56086136e-05j
 -4.45548755e-05+8.68285929e-06j ...  4.09482868e-05-2.84103581e-05j
  9.25010842e-06-1.98329150e-05j  1.32234330e-05-3.84064752e-05j]


In [56]:
z

array([-4.96781848e-12-9.55082731e-12j,  5.22574572e-12-6.49533508e-12j,
        1.04555171e-11+2.52036037e-12j, ...,
        2.02980688e-12+9.94928708e-12j, -9.82058599e-12+4.72396122e-12j,
       -5.57308601e-12-8.63236968e-12j])

In [7]:
w_vec = np.linspace(Q_h-1e-2,Q_h+1e-2,1000)


array([1.81902103e-03, 1.45186871e-03, 5.24934093e-04, 6.09497617e-04,
       1.51710894e-03, 1.84801498e-03, 1.47144789e-03, 5.27437581e-04,
       6.25275221e-04, 1.54536279e-03, 1.87806013e-03, 1.49175767e-03,
       5.30062582e-04, 6.41599459e-04, 1.57463374e-03, 1.90920957e-03,
       1.51283423e-03, 5.32813882e-04, 6.58499722e-04, 1.60497498e-03,
       1.94152038e-03, 1.53471656e-03, 5.35696726e-04, 6.76007542e-04,
       1.63644370e-03, 1.97505400e-03, 1.55744668e-03, 5.38716850e-04,
       6.94156787e-04, 1.66910144e-03, 2.00987665e-03, 1.58106994e-03,
       5.41880517e-04, 7.12983884e-04, 1.70301450e-03, 2.04605969e-03,
       1.60563527e-03, 5.45194566e-04, 7.32528068e-04, 1.73825441e-03,
       2.08368023e-03, 1.63119560e-03, 5.48666457e-04, 7.52831657e-04,
       1.77489842e-03, 2.12282157e-03, 1.65780818e-03, 5.52304330e-04,
       7.73940360e-04, 1.81303008e-03, 2.16357390e-03, 1.68553505e-03,
       5.56117068e-04, 7.95903630e-04, 1.85273988e-03, 2.20603499e-03,
      